
<ul id="navbar" class="nav" >
     <li class="nav-item "><a class="nav-link text-white" href="<?= $_refer(""); ?>">Home</a></li>
    <li  class="nav-item"><a class="nav-link text-white" href="<?= $_refer(""); ?>">Categorias</a></li>
    <li  class="nav-item"><a class="nav-link text-white" href="<?= $_refer(""); ?>">Sobre</a></li>
    <li class="nav-item"><a class="nav-link text-white" href="<?= $_refer(""); ?>">Contato</a></li>

</ul>
