
<div id="title-container">
    <h1>Blog codar</h1>
    <p>O seu Blod de programação</p>
</div>

<div id="posts-container">

    

    <?php foreach($posts as $post):?>

        <div class="post-box">
           <img src="<?= $_img($post['img']); ?>" alt="<?= $post['title']?>">
           <h2 class="post-title">
               <a href="<?=$base_url?>post.php/id=<?= $post['id']?>"><?= $post['title']?></a>
            </h2>
            <p class="post-description"><?=$post['description']?></p>
        </div>
    <?php endforeach?>
</div>
